### ISSUE TITLE
Retry to detect the Extension on failing to do so

### ISSUE THREAD

**Issue by jloehr** [jloehr/HID-Wiimote#11]
Sometimes the Extension type is not reported back correctly by the Wii Remote. This seems due to a hardware glitch and a "partially connected" state. Current workaround is to re-plug in the extension multiple times. However this hardly occurs when playing on the Wii/Wii U, so there is a solution to that.

Attempt is to constantly retry to detect the extension type until a correct one is detected or the extension is removed.

**Comment by jloehr** [comment]
This hopefully fixes #10

**Comment by jinwk00** [comment]
Does this mean you fixed my problem in #10?

**Comment by jloehr** [comment]
Yes

**Comment by jinwk00** [comment]
Glad to hear about that. Can you remind me of release date?
2016. 1. 12. 오전 5:27에 "Julian Löhr" <notifications@github.com>님이 작성:

**Comment by jloehr** [comment]
http://julianloehr.de/hid-wiimote/gamepad/0.2.6/ :wink:
