### ISSUE TITLE
Check the Balance Board implementation

### ISSUE THREAD

**Issue by jloehr** [jloehr/HID-Wiimote#13]
The Wii Balance Board reports its sensor data with 2 bytes each sensor. The driver only uses the most significant byte and this may be too less sensitive.
Either each primary axix is using a 2 byte data range or the sensor data is cropped to the least significant byte.

**Comment by programminghoch10** [comment]
I'd like it when you could make to axes: forward/backward and left/right
I want to use it for an car game as accelerator and break

**Comment by jloehr** [comment]
That is the current implementation.
In 0909fea9d5f552a2283e9ed123698b61ec340a3d i changed it to use the least significant byte and crop the values.
However i am not able to test the Balance Board, as i currently don't have one around. Therefore the Balance Board implementation is experimental and may not work properly.

**Comment by jloehr** [comment]
As mentioned in the commit message; the current implementation is using absolute values cropped at 34Kg. So i a person has body weight of 68Kg or less it is not able to achieve the full value range. Therefore this implementation should be changed at some point in the future to use relative values taking the body weight into account.
