### ISSUE TITLE
Nunchuck

### ISSUE THREAD

**Issue by programminghoch10** [jloehr/HID-Wiimote#14]
There is a little problem:
When i plug in the nunchuck then all the buttons change and the nunchuck and controller button field (i don't know how it's called) also change witch means that it isn't calibrated and is a little bit at the right so i can't use the nunchuck properly

**Comment by jloehr** [comment]
The button mapping change is intended behavior. If no Extension is plugged in you are supposed to hold the Wiimote horizontally with both hands. When you plug in the Nunchuck, it is inteded to hold the Wiimote vertically in one hand and the Nunchuck in the other (as you do when you play a Wii Game with Nunchuck).
As of Wiibrew, the Nunchuck (as well as every other Extension) is calibrated, when it is plugged in. So the position of the analog stick the very moment it is plugged in, is taken as null state. If it is still off later on, you can recalibrate the controller through the Windows Gamepad properties dialog on the settings tab.
