### ISSUE TITLE
Guitar Hero Extensions Not entirely functional

### ISSUE THREAD

**Issue by MikeMatt16** [jloehr/HID-Wiimote#15]
One button on the Guitar Hero Drum Kit and Guitar Hero Guitar extensions are not being recognized by the device driver. On both extensions, I believe that the 3rd button is not being recognized. The Drum pad has 5 pads. These pads represent buttons one through 5. The 3rd pad (Blue Pad) does not trigger a button press in the Game Controller Test dialog. The same applies to the guitar. The 5 finger buttons represent 1 through 5, and the 3rd button (Yellow Button) does not trigger a button press in the Game Controller Test Dialog.

I have used both instruments with GlovePIE which maps the Game pad buttons to keyboard key presses, and all of the guitar buttons and drum pads work using it.

**Comment by jloehr** [comment]
Fixed https://www.julianloehr.de/hid-wiimote/gamepad/0.2.7.3/
:smile:
