### ISSUE TITLE
Can't use balance board

### ISSUE THREAD

**Issue by arpruss** [jloehr/HID-Wiimote#18]
Wiimote+nunchuck works fine on my Win 8.1 x64 system, but the balance board doesn't. The front button registers as button 3, but joy.cpl doesn't show any movement on any of the axes.

**Comment by jloehr** [comment]
Have you checked the Game Controllers Properties Test Dialog for the axes movement?

I can't confirm it with the board i have, but another user seems to have a similar issue.
In April i'll get another board, but until then i won't be able to fix this, as i can't reproduce it.

**Comment by jloehr** [comment]
Ok, i tested two Wii Balance Boards on Windows 8.1 64Bit and Windows 10 64Bit. Both boards work on either system.

If the issue still exists, can you try to remove/uninstall all Wiimote Drivers from your system and install the latest version. Then please check the Properties Test Dialog.

Additionally you have to stand on the board to get some readings, as the value calculation uses the full sensor value range. I.e. you need to put 68Kg on one edge of the board to get the max value reading.
