### ISSUE TITLE
Gamepad Driver does not receive input and shows 32 buttons and no axis

### ISSUE THREAD

**Issue by BOTButtcheeks** [jloehr/HID-Wiimote#20]
I installed the wiimote driver and the 3rd and 4th lights are solid, however when I go to the game controllers settings it shows this:

![image](https://cloud.githubusercontent.com/assets/12685716/15334028/e41cda22-1c9e-11e6-80fc-7de5571c12f0.png)

and does not show any input

Windows 10 Pro 64-bit (10.0, Build 10586)

**Comment by jloehr** [comment]
The title of the dialog says "Media Keys", so i assume it's for another device or another driver is interfering.
