### ISSUE TITLE
Configuration of Wiimote (Mouse, Keyboard, Joypad -> DirectInput, XInput, Raw)

### ISSUE THREAD

**Issue by Papermanzero** [jloehr/HID-Wiimote#21]
I read a about a configuration application to configure the wiimote.
The configuration shall include button mappings (Directinput and Xinput).
However I would like to know if it is possible to add a mouse/keyboard configuration.
Means to adjust the dead zone of the mouse pointer, to map mouse/keyboard keys to the wiimote buttons and movement/tilt sensors.
Especially the mouse pointer would be interesting. Many applications like browser, apps, games could be controlled via wiimote. However no solution (dolphin bar or Touchmote) have an appropriate configuration to have a smooth mouse cursor movement. The mouse cursor is always shaking due to the sensitivity of the wiimote.

**Comment by jloehr** [comment]
Are you talking about my planned configuration/control app? If so, then yes it will include a mouse mode, to use the Wiimotes IR as mouse pointer.
Also i would like to have free button mapping, though that won't be coming in the first update. First step is going to finish up the control app in a basic form. Then i will start on that advanced stuff.

**Comment by Papermanzero** [comment]
This is exactly what I am talking about.
Sounds great.
