### ISSUE TITLE
Dolphin Bar Support

### ISSUE THREAD

**Issue by Papermanzero** [jloehr/HID-Wiimote#23]
Would it be possible to support the dolphin bar.
Currently the Wiimote connects as directinput device, if the dolphin bar is used.
Would be great if the HID driver together with the configuration tool can be also used with the dolphin bar.

**Comment by jloehr** [comment]
Nope, the Dolphin Bar acts as composite USB Device and handles all the Bluetooth Wiimote stuff on its hardware. So there is no way to intercept that, except providing a custom firmware.
I am not sure how it exposes the different modes, but i think each Wiimote is present as single HID, that supports all four modes. So one could provide a driver that hooks onto that. But then you would run the Dolphin Bar in Mode 4 all the time and do all the different modes as software per driver. Though then it acts merely as Bluetooth Dongle.

**Comment by Papermanzero** [comment]
The benefit of the Dolphin Bar is the automatic connection.
No pairing process etc. If a wiimote is paired with the Dolphin bar it automatically connects with it as soon as the user presses a button.
If this can be implemented with the driver as well, then it is perfect.
Otherwise it would be great to make the configuration tool compatible with Mode 4 of dolphin bar.

**Comment by jloehr** [comment]
The one button reconnect is set up by providing the proper Bluetooth Auth Key/PIN. Unfortunately my driver is loaded after the Bluetooth connection is established (including the Auth/PIN). I already did some research and it seems to be impossible to intercept the Auth process (without writing your own Bluetooth Stack) or renew the authentication from a profile driver. However it seems there is a User-Mode API that i have yet to test. Anyway proper authentication is something i would like to add to my driver, so it makes the pairing process easier.

Adding support for the DolphinBar is currently completely out of scope for this project. This projects main goal is to give Bluetooth connected Wiimotes proper support to use them in games (or other applications). When this goals is somehow reached, i will reconsider adding DolphinBar support, though that will be in the far future.
