### ISSUE TITLE
Windows 10 Connectivity Issues

### ISSUE THREAD

**Issue by ShiningKnightLight** [jloehr/HID-Wiimote#27]
Hi Julian, I just wanted to say thank you for such awesome work so far on getting the Wiimote working in Windows, it's very much appreciated. 

I looked around previously for GlovePIE and couldn't find it, and FreePIE sort of worked at least with buttons but didn't include IR camera support, which is what I'm looking to use. I'm really wanting to use the Wiimote as an IR Mouse in Windows 10 on a 3 monitor setup. I'm running Windows 10 on 2 Desktop PCs, a tablet, and a MacBook Pro (via Bootcamp) at home.

The issue I'm having is I can't seem to get the Wiimote working right in Windows 10 on any PC in the mix. Also this is an older non -TR Wiimote, it's an RVL-CNT-01.

Steps:
- Downloaded the IR-Mouse 0.2.6.2 64-bit package.
- Went to cmd terminal as administrator and ran Bcdedit.exe -set TESTSIGNING ON
- Rebooted (now I get "Test Mode" in the lower right of Windows)
- Ran TinyInstaller as admin.
- Everything looks like it installs fine.
- I go to pair it, press 1 and 2 rapidly on the Wiimote, it takes several minutes for it to pick up that the Wiimote is there, eventually I get the pairing screen, hit next, by this point it MAY have already turned off, and if so that looks like it causes a lot of problems with pairing, sometimes I have to repeat the pairing process.
- After the first install it got stuck on loading the drivers, eventually ended. I was getting no results still, so I attempted to reboot.
- When I go to either Bluetooth screen (under Devices and Printers under the old Control Panel, or under Settings / Bluetooth), it looks as though the device is paired, but it's not working, no blue light to show connectivity after the first time.
- Under Device Manager it shows the Wiimote Device with your driver loads fine under Human Interface Devices, looks like the Bluetooth device it's still using Microsoft's drivers, but when I look under Devices and Printers at the hardware properties it shows HID-compliant mouse, Nintendo RVL-CNT-01, then Wiimote Device (your driver).
- Despite that things look fine (or at least I assume they are), no movement occurs with the mouse and none of the buttons seem to work (also I don't know which one should be the left click).

Also I tried downloading the source from here and compiling in VS2015 Community. After some work I got things compiling everything up to the BuildAndZip project. I'm having issues with the BuildAndZip project on both Debug and Release. It simply doesn't find the right directories on Debug because the project is hardcoded to look for a Release directory somewhere it looks like, and on Release it's looking for a DpInst.exe that seems to no longer be included in the Windows 10 WDK, and all of my SDKs are targeting Windows 10 SDK/WDK since I'm on Windows 10. I'd like to also be able to use the debugger but I have no idea yet how to get this going on my machine(s) as this is my first time ever delving into Windows drivers. 

If I can get all this to work, I want to delve into some other gaming related things, like turning my Windows 10 tablet into a virtual mouse/keyboard/joystick/midi/flightsim controller as well for my desktops via somehow making a virtual USB driver (not as an RDP client, but being able to design button/axes layouts for controls on the tablet itself and have it generate the HID and communicate with the desktops as a virtual controller).

**Comment by jloehr** [comment]
Regarding building it yourself, you can remove the BuildAndZip Build event command. Zipping is only required for me to have some nicely zipped packages for release.

About the connecting issue: 
* Remove the still paired/connected device in Devices and Printers via right click.
* Start a new pairing process. 
* While the LEDs on the Wii Remote are flashing, continuously press the A button on the Wii Remote to keep it awake. 
* The pairing is successful if the LEDs stop flashing and some or all of it stay lit. If not disconnect & remove the Bluetooth device from Windows and start over. 

Sometimes pairing takes couple of tries.

The ongoing driver loading in the Settings can be ignored. The important indicator for a successful connection is that LEDs stay lit.
