### ISSUE TITLE
What would a signing cert cost?

### ISSUE THREAD

**Issue by axfelix** [jloehr/HID-Wiimote#28]
I'd like to help you crowdfund a driver certificate if possible, I'm sick of having to reboot Windows 10 to load this :)

**Comment by Aventura5** [comment]
I was under the impression it was in the low thousands (which is crazy) but
DigiCert which Microsoft implicitly recommends offers EV code signing certs
for 224 for one year, and slightly less per year for 2 or 3 years. You need
EV not standard for drivers if I understood Microsoft docs right.
Here's the order page for DigiCert:
https://www.digicert.com/order/order-1.php
and the MS docs:
https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate


>
>

**Comment by axfelix** [comment]
Good to know! I'd be willing to contribute $40 or $50... do you want to try putting together a patreon or something?

**Comment by jloehr** [comment]
Hi,
the driver signing procedure is actually quite complicated.
As far as i am understanding it, one needs a non-EV code sign certificate to sign the driver packages. That's sufficient for Win 8.1 and below. 
Starting with Win 10, one needs a EV Code Cert to open a MS Hardware Dev Account. There you upload you previously non-EV signed package. That package is then signed by MS with their certificate and after downloading it, it is then ready for Win10.
There are some exceptions and rules about different certificates, old certificates and drivers, etc., but even professional driver developers are still confused by that.

Anyhow for Win 10 (and any future Windows Version) i would need a EV code cert to begin with. That starts at around 500$ per year (be sure to check the "EV code signing certificate" and not EV-SSL certs). A handful of people are indeed willing to donate and contribute for a EV Cert. So one way or the other we may get enough funds for a certificate. However there are two issues, one small, one big.
The big one is, i am not certain that i am eligible for a EV Cert. Most CA's don't provide EV Certs to individuals and i am neither a freelancer nor self-employed.
The smaller issue is that i am currently not much progressing with this project. So i would feel bad for taking donations or doing patreon, knowing i am not returning anything for it.

@nefarius: Is my understanding about driver signing correct? Maybe you could elaborate how you got your EV Cert.

**Comment by nefarius** [comment]
@jloehr [I went through hell and back with this damn certification requirements](https://vigem.org/2017/02/05/windows-driver-signing-bullshit/) but I found a better way that's mpt documented anywhere! I'll explain later 😉
