### ISSUE TITLE
Guitar Hero analog stick acting as buttons

### ISSUE THREAD

**Issue by RedTheBlueColor** [jloehr/HID-Wiimote#31]
The guitar hero analog stick is the only thing functioning on the guitar and it triggers random buttons even when still.
![gh3bug](https://user-images.githubusercontent.com/13177944/29335438-446f6ace-81d0-11e7-9d43-d7db9cb574a1.PNG)

**Comment by jloehr** [comment]
What version are you using? If 0.3.0.0, does the Control Center lists it as "Guitar Hero"?

**Comment by RedTheBlueColor** [comment]
It lists it as Guitar Hero and when changing the check boxes it has the same effect.

**Comment by jloehr** [comment]
Found it, i broke the buttons. Uh, also i figured why Whammy and Touch Bar were broken.
Thanks for reporting 👍
