### ISSUE TITLE
Does HID-Wiimote support more than one wiimote at the same time?

### ISSUE THREAD

**Issue by Grauen** [jloehr/HID-Wiimote#32]
I'd like to use more than one wiimote at the same time, e.g. to use it with MAME-Multiplayer games.

Is this possible? (Update: Next time Ill read something through before asking ;) 
If not this would be a killing feature!

**Comment by jloehr** [comment]
Yeah, each Wii Remote is a distinct input device/game controller. So if you connect two Wii Remotes, you get two controllers.
