### ISSUE TITLE
Driver error when connecting to Windows 10 

### ISSUE THREAD

**Issue by rodolforg** [jloehr/HID-Wiimote#34]
Everytime I try to add/pair a wiimote, it gives me this driver error (after it logs as successfully configured):

```
Device BTHENUM\{00001124-0000-1000-8000-00805f9b34fb}_VID&0002057e_PID&0306\7&34e2c4fd&0&0021BD21F413_C00000000 had a problem starting.

Driver Name: oem78.inf
Class Guid: {745A17A0-74D3-11D0-B6FE-00A0C90F57DA}
Service: HIDMiniport
Lower Filters: HIDWiimote
Upper Filters: 
Problem: 0x34
Problem Status: 0xC0000428

```

**Comment by jloehr** [comment]
That error is related to the Driver Signature Verification. Can you confirm that the Driver Signature Verification is properly turned off on your system?

**Comment by rodolforg** [comment]
Yes, you're right.
By following the instruction list, I thought thst installing the certificate on Control Center was enough.
