### ISSUE TITLE
Minor HID descriptor issue

### ISSUE THREAD

**Issue by abend0c1** [jloehr/HID-Wiimote#38]
In HID-Wiimote/HID Wiimote/HIDDescriptors.c I think the following:

` 	0x65, 0x12,                    //   UNIT (SI Rot:Angular Pos)`

...should be:

`	0x65, 0x14,                    //   UNIT (English Rot:Angular Pos in Degrees)`

...given that the logical values that the usage can have is 1 to 8, and the corresponding physical values are 0 to 315 in 45 degree increments i.e. physical = (logical - 1) * 45

The SI rotational unit is radians not degrees. Probably doesn't matter much...just sayin' :)

**Comment by jloehr** [comment]
Indeed, thanks for pointing that out 😄
