### ISSUE TITLE
Doppelbelegung "WiiMote + Nunchuck"

### ISSUE THREAD

**Issue by BenjaminRenz** [jloehr/HID-Wiimote#41]
Wenn an die WiiMote ein Nunchuck verbunden wird, ist die A-Taste der WiiRemote als auch die Hometaste auf den "Virtuellen Button" 1 gemappt.

**Comment by jloehr** [comment]
https://github.com/jloehr/HID-Wiimote/blob/e064a81b793abdda1fd0165caa2931a21bd2c8d0/HID%20Wiimote/WiimoteToHIDParser.c#L404

must be changed to

` ParseButton(WiimoteState->WiiRemoteState.CoreButtons.Home, &GamepadReport->Buttons[1], 0);`
