### ISSUE TITLE
Wii MotionPlus Inside supported?

### ISSUE THREAD

**Issue by BenjaminRenz** [jloehr/HID-Wiimote#42]
I have a wiiremote with motion plus connected with your driver. But I can't find the additional axis of the motion plus gyros. Is MotionPlus (inside the remote) supported?

**Comment by jloehr** [comment]
Yes and No. It is supported in the sense, that it will be ignored, so Wii Remotes with Motion Plus (inside) work. However the gyro data is currently not utilized at all.
