### ISSUE TITLE
Error when installing the driver.

### ISSUE THREAD

**Issue by itsledanny** [jloehr/HID-Wiimote#46]
I recorded the error and posted on youtube, you can see in this link:

https://www.youtube.com/watch?v=fwXpb1Aqmek&feature=youtu.be

**Comment by jloehr** [comment]
Hey, thanks for the video. That's a real help.
It is the same issue I am already investigating under #43. Therefore I am closing this issue, to have just on open issue for this matter.

**Comment by jloehr** [comment]
Would you mind trying a possible fix, by installing the [Microsoft Visual C++ Visual Studio 2017](https://go.microsoft.com/fwlink/?LinkId=746572) and then trying again to open the HID Wiimote Control Center.

**Comment by itsledanny** [comment]
It worked for me. Thank you very mutch dude!
