### ISSUE TITLE
Code 52 when selecting driver

### ISSUE THREAD

**Issue by ndrew222** [jloehr/HID-Wiimote#48]
I have test mode enabled, and I followed the instructions on the website carefully, but after selecting "Update Driver" > "Browse my computer for driver software" > "Let me pick from a list of available driver software" > "Wiimote Device" > "Next"

I get
"Windows cannot verify the digital signature for the drivers required for this device. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (Code 52)"

Not too sure how to handle this.

**Comment by ndrew222** [comment]
nvm didn't reboot. My bad

**Comment by milovincent** [comment]
Code 52 still present for me even after rebooting.

**Comment by yllekz** [comment]
I'm also getting this on Windows 10 21H1. Seems the OS is blocking the driver from working.
