### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by coltar00** [jloehr/HID-Wiimote#49]
im on windows 10 64bit after running installation it showed that "Julian Lohr (HID Wiimote) Install Failed".
I have tried to install multiple times i would appreciate any help.

**Comment by madser123** [comment]
I have the same problem.

**Comment by jloehr** [comment]
Closing this issue due to its age.

For future visitors with similar issues, make sure to enable `Test Mode` (check and disable `Secure Boot` as well) and to install the Driver Certificate.
