### ISSUE TITLE
Wiimote as Gamepad

### ISSUE THREAD

**Issue by Scoobert023** [jloehr/HID-Wiimote#51]
I have discovered that when trying to play with a game without controller support, the wiimote never works. This is odd to me because I have tried using it with programs like Xpadder or JoytoKey, which emulate the wiimote with keyboard keys, but i guess the games still view it as a controller. I was just wondering if there was any way that the wiimote could be viewed as a keyboard device rather than a game controller or mouse. Or maybe is there some way i can remap the d-pad mouse option for the buttons on the wiimote.

**Comment by jloehr** [comment]
Indeed games that do not support controller input won't work. Mapping tools like Joy2Key are your way to go on this issue.
