### ISSUE TITLE
Unable to change driver

### ISSUE THREAD

**Issue by joshop** [jloehr/HID-Wiimote#52]
I installed it successfully and even managed to pair my Wiimote, but it's still using the old driver   from Microsoft. However, when I go to "Update Driver" and select to pick from a list of available driver software, only "Bluetooth Device" (Microsoft driver) is showing up, rather than "Wiimote Device". I have also disabled Driver Signature Verification.

**Comment by albianto** [comment]
Mine worked even if that did not change. After you pair your Wiimote, right click on it in the windows control panel and click the first menu item from the top. It should pop up a window that has the driver in the list and you can access the settings.

**Comment by jloehr** [comment]
Also make sure `Secure Boot` is disabled, `Test Mode` is enabled and active and the Certificate from the Installer is installed. Otherwise the driver may not be picked as default driver or may fail to load.
