### ISSUE TITLE
"bundled" axis input for Classic Controller analog triggers

### ISSUE THREAD

**Issue by larsiusprime** [jloehr/HID-Wiimote#7]
(just putting this here for reference)

The analog triggers on the classic controller (L and R) are currently bound to "z rotation" (axis 4?) such that L is half the range (-1,0) and R is the other half (0,1). This could be worked around in a framework API, but it does mean both inputs can't be pressed at once unambiguously. Recommend splitting into two inputs, each of the full (-1,1) range.

**Comment by jloehr** [comment]
Already fixed with #6 :)

**Comment by larsiusprime** [comment]
Great!
